LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "Have you ever heard of the parallel\n"
	.string "universe, Earth?\p"
	.string "The people there are like us, but\n"
	.string "they're not made out of code;\l"
	.string "they're made out of Water!\p"
	.string "They're not even like Water Pokemon,\n"
	.string "either, they're just like these human-\l"
	.string "shaped lakes walking around.\p"
	.string "They also have to like, fill up their\n"
	.string "gooey bodies with more, because it\l"
	.string "gets used up or something.\p"
	.string "Wild to think about, isn't it?$"


LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "There's a deep underwater trench\n"
	.string "between MOSSDEEP and SOOTOPOLIS.\p"
	.string "That's what someone told me, anyway.$"

